#!/usr/bin/env /Users/thanpolas/.nvm/versions/node/v6.10.0/bin/node

// a simple static webserver
var http = require('http');
var serveStatic = require('serve-static'); // https://www.npmjs.com/package/serve-static
var path = require('path');
var exec = require('child_process').exec;
var finalhandler = require('finalhandler');

var filename = path.basename(process.argv[1]);
process.argv.forEach(function(val, index, array){
  if (1 >= index)
    return;
  if (val.match(/(\-h|\-help)/))
    showHelp();
});

var port = process.argv[2] || 5555;
var userpath = process.argv[3] || '';


//var dir = path.resolve(findup(process.cwd(), 'grunt.js'), '../node_modules/grunt');
var dir = path.resolve(process.cwd(), userpath);


console.log('Starting static web server...\n');
console.log('Web root: ' + dir);
console.log('Port    : ' + port);
console.log('Going to   : http://localhost:' + port);
try {

  var serve = serveStatic(dir);
  var server = http.createServer(function onRequest(req, res) {
    serve(req, res, finalhandler(req, res))
  });
  server.listen(port);

  exec('open -a Google\\ Chrome\\ Canary http://localhost:' + port,
    function(error, stdout, stderr){
      if (error && error.length) {
        console.log('Launching Chrome Canary error:\n' + error);
      }
    });

} catch (e) {
  console.log(e);
}

function showHelp()
{
  console.log('Usage: ' + filename + ' [port] [path]\n');
  process.exit(1);
}